"""create glucose_readings table

Revision ID: ee24908c16e1
Revises: 
Create Date: 2026-09-30 16:09:55.929376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee24908c16e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glucose_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_timestamp', sa.DateTime(), nullable=False),
    sa.Column('record_type', sa.SmallInteger(), nullable=False),
    sa.Column('historic_glucose_mgdl', sa.Numeric(), nullable=True),
    sa.Column('scan_glucose_mgdl', sa.Numeric(), nullable=True),
    sa.Column('rapid_acting_insulin_units', sa.Numeric(), nullable=True),
    sa.Column('long_acting_insulin_units', sa.Numeric(), nullable=True),
    sa.Column('carbohydrates_grams', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_timestamp', 'record_type', name='uq_glucose_reading_timestamp_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glucose_readings')
    # ### end Alembic commands ###
