"""create sensor_log_entries table

Revision ID: f4cd3741a448
Revises: a8360cc2f037
Create Date: 2026-10-01 00:40:32.307251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4cd3741a448'
down_revision: Union[str, Sequence[str], None] = 'a8360cc2f037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_status_code', sa.String(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_status_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_log_entries')
    # ### end Alembic commands ###
